### ISSUE TITLE
Push notifications not reliable

### ISSUE THREAD

**Issue by provokateurin** [provokateurin/nextcloud-neon#467]
I receive about 50% or so of push notifications. I'm pretty sure that it's the fault of the app and not of my setup or distributor because other apps seem to get 100% of the push notifications.

**Comment by provokateurin** [comment]
The crash of the permission handler is not great but can't be the source of the problem.

**Comment by provokateurin** [comment]
Ok confirmed, if the second error doesn't happen the notification is displayed successfully.

I also found
```log
07-14 08:05:03.053 13941 13964 E flutter : [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(quick_action_getlaunchaction_no_activity, There is no activity available when launching action, null, null)
07-14 08:05:03.053 13941 13964 E flutter : #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652)
07-14 08:05:03.053 13941 13964 E flutter : #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310)
07-14 08:05:03.053 13941 13964 E flutter : <asynchronous suspension>
07-14 08:05:03.053 13941 13964 E flutter : #2      QuickActionsAndroid.initialize (package:quick_actions_android/quick_actions_android.dart:32)
07-14 08:05:03.053 13941 13964 E flutter : <asynchronous suspension>
07-14 08:05:03.053 13941 13964 E flutter : #3      _NeonAppState.initState.<anonymous closure> (package:neon/src/app.dart:93)
07-14 08:05:03.053 13941 13964 E flutter : <asynchronous suspension>
07-14 08:05:03.053 13941 13964 E flutter : 
```
